### PR TITLE
Is Krusader stil being developed?

### PR DESCRIPTION
**Pull request by dandv**
Wanted to get in touch but the Issues tab is disabled.

Wondering what the status of Krusader is. I see commits, but no new versions.

http://askubuntu.com/questions/779668/is-krusader-still-being-developed

### CODE REVIEW

**Comment by abika** [comment]
The Website (http://www.krusader.org/) is currently down, but development is going on at https://phabricator.kde.org/project/profile/79/ .

Also notice this: https://techbase.kde.org/Development/Git/GitHub_Mirror

**Comment by dandv** [comment]
Please reconsider the PR policy at https://community.kde.org/Infrastructure/Github_Mirror

GitHub has orders of magnitude more contributors than KDE, and makes it [far, far easier to contribute](https://wiki.dandascalescu.com/essays/pita-threshold).

**Comment by dandv** [comment]
I've just read [this gem](https://bugs.kde.org/show_bug.cgi?id=363648#c1) on Krusader.org being down:

> Please note that KDE Web Team has no control or association with krusader.org, so there is nothing we can do here.
> 
> Reassigning back to the Krusader developers, who should in theory at least have some association with it.

**Comment by tsdgeos** [comment]
Thanks for your contribution :)

This repository is a mirror a KDE repository. For this reason we can't accept contributions through Github. Please see https://community.kde.org/Infrastructure/Github_Mirror for details on how to contribute to this and other KDE projects.

**Pull request closed without merging**
